name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/docker-login@v1
      with:
        login-server: yourACRname.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}    

    - name: Build the Docker image
      run: |
        cd ContainerDemoAPI
        docker build . --file Dockerfile --tag webappwebapi.azurecr.io/webapi:${{ github.run_number }}
        docker push docker push webappwebapi.azurecr.io/webapi:${{ github.run_number }}

